const tarotCards = [
    { id: 0, name: "Шут", nameEn: "The Fool", arcana: "major", keywords: ["новые начинания", "спонтанность", "свобода"], meaning: "Новое путешествие, невинность, спонтанность" },
    { id: 1, name: "Маг", nameEn: "The Magician", arcana: "major", keywords: ["сила воли", "мастерство", "концентрация"], meaning: "Сила воли, мастерство, концентрация" },
    { id: 2, name: "Жрица", nameEn: "The High Priestess", arcana: "major", keywords: ["интуиция", "тайна", "подсознание"], meaning: "Интуиция, подсознание, тайные знания" },
    { id: 3, name: "Императрица", nameEn: "The Empress", arcana: "major", keywords: ["плодородие", "изобилие", "природа"], meaning: "Изобилие, плодородие, гармония с природой" },
    { id: 4, name: "Император", nameEn: "The Emperor", arcana: "major", keywords: ["власть", "структура", "контроль"], meaning: "Власть, структура, авторитет" },
    { id: 5, name: "Иерофант", nameEn: "The Hierophant", arcana: "major", keywords: ["традиции", "обучение", "духовность"], meaning: "Традиции, духовное обучение" },
    { id: 6, name: "Влюбленные", nameEn: "The Lovers", arcana: "major", keywords: ["любовь", "гармония", "выбор"], meaning: "Любовь, гармония, важный выбор" },
    { id: 7, name: "Колесница", nameEn: "The Chariot", arcana: "major", keywords: ["победа", "контроль", "решимость"], meaning: "Победа, решимость, контроль" },
    { id: 8, name: "Сила", nameEn: "Strength", arcana: "major", keywords: ["смелость", "сострадание", "терпение"], meaning: "Внутренняя сила, терпение" },
    { id: 9, name: "Отшельник", nameEn: "The Hermit", arcana: "major", keywords: ["самоанализ", "мудрость", "уединение"], meaning: "Самоанализ, поиск истины" },
    { id: 10, name: "Колесо Фортуны", nameEn: "Wheel of Fortune", arcana: "major", keywords: ["перемены", "судьба", "циклы"], meaning: "Перемены, поворот судьбы" },
    { id: 11, name: "Справедливость", nameEn: "Justice", arcana: "major", keywords: ["справедливость", "правда", "закон"], meaning: "Справедливость, баланс" },
    { id: 12, name: "Повешенный", nameEn: "The Hanged Man", arcana: "major", keywords: ["пауза", "сдача", "новая перспектива"], meaning: "Пауза, новый взгляд" },
    { id: 13, name: "Смерть", nameEn: "Death", arcana: "major", keywords: ["трансформация", "конец", "возрождение"], meaning: "Трансформация, конец цикла" },
    { id: 14, name: "Умеренность", nameEn: "Temperance", arcana: "major", keywords: ["баланс", "умеренность", "гармония"], meaning: "Баланс, умеренность" },
    { id: 15, name: "Дьявол", nameEn: "The Devil", arcana: "major", keywords: ["искушение", "зависимость", "материализм"], meaning: "Искушение, материальная привязанность" },
    { id: 16, name: "Башня", nameEn: "The Tower", arcana: "major", keywords: ["разрушение", "внезапные перемены", "освобождение"], meaning: "Внезапные перемены, разрушение иллюзий" },
    { id: 17, name: "Звезда", nameEn: "The Star", arcana: "major", keywords: ["надежда", "вдохновение", "спокойствие"], meaning: "Надежда, вдохновение" },
    { id: 18, name: "Луна", nameEn: "The Moon", arcana: "major", keywords: ["иллюзии", "интуиция", "страхи"], meaning: "Интуиция, скрытые страхи" },
    { id: 19, name: "Солнце", nameEn: "The Sun", arcana: "major", keywords: ["радость", "успех", "жизненная сила"], meaning: "Радость, успех, жизнелюбие" },
    { id: 20, name: "Суд", nameEn: "Judgement", arcana: "major", keywords: ["возрождение", "призвание", "прощение"], meaning: "Возрождение, внутренний зов" },
    { id: 21, name: "Мир", nameEn: "The World", arcana: "major", keywords: ["завершение", "целостность", "достижение"], meaning: "Завершение, достижение цели" },
    { id: 22, name: "Туз жезлов", suit: "wands", arcana: "minor", keywords: ["вдохновение", "новая идея", "энергия"], meaning: "Новое вдохновение, творческая энергия" },
    { id: 23, name: "Двойка жезлов", suit: "wands", arcana: "minor", keywords: ["планирование", "решение", "будущее"], meaning: "Планирование будущего, выбор пути" },
    { id: 24, name: "Тройка жезлов", suit: "wands", arcana: "minor", keywords: ["расширение", "прогресс", "перспективы"], meaning: "Прогресс, расширение горизонтов" },
    { id: 25, name: "Четверка жезлов", suit: "wands", arcana: "minor", keywords: ["празднование", "гармония", "дом"], meaning: "Празднование, стабильность" },
    { id: 26, name: "Пятерка жезлов", suit: "wands", arcana: "minor", keywords: ["конфликт", "соревнование", "борьба"], meaning: "Конфликт, конкуренция" },
    { id: 27, name: "Шестерка жезлов", suit: "wands", arcana: "minor", keywords: ["победа", "признание", "успех"], meaning: "Победа, признание заслуг" },
    { id: 28, name: "Семерка жезлов", suit: "wands", arcana: "minor", keywords: ["защита", "настойчивость", "вызов"], meaning: "Защита своих позиций" },
    { id: 29, name: "Восьмерка жезлов", suit: "wands", arcana: "minor", keywords: ["скорость", "действие", "движение"], meaning: "Быстрое движение вперед" },
    { id: 30, name: "Девятка жезлов", suit: "wands", arcana: "minor", keywords: ["устойчивость", "выносливость", "границы"], meaning: "Настойчивость, защита границ" },
    { id: 31, name: "Десятка жезлов", suit: "wands", arcana: "minor", keywords: ["бремя", "ответственность", "нагрузка"], meaning: "Тяжелое бремя ответственности" },
    { id: 32, name: "Паж жезлов", suit: "wands", arcana: "minor", keywords: ["исследование", "энтузиазм", "новости"], meaning: "Новые идеи, энтузиазм" },
    { id: 33, name: "Рыцарь жезлов", suit: "wands", arcana: "minor", keywords: ["энергия", "страсть", "приключения"], meaning: "Энергичное действие" },
    { id: 34, name: "Королева жезлов", suit: "wands", arcana: "minor", keywords: ["уверенность", "харизма", "независимость"], meaning: "Уверенность, харизма" },
    { id: 35, name: "Король жезлов", suit: "wands", arcana: "minor", keywords: ["лидерство", "видение", "предпринимательство"], meaning: "Лидерство, предпринимательский дух" },
    { id: 36, name: "Туз кубков", suit: "cups", arcana: "minor", keywords: ["любовь", "эмоции", "новые чувства"], meaning: "Новые эмоции, любовь" },
    { id: 37, name: "Двойка кубков", suit: "cups", arcana: "minor", keywords: ["партнерство", "связь", "гармония"], meaning: "Гармоничные отношения" },
    { id: 38, name: "Тройка кубков", suit: "cups", arcana: "minor", keywords: ["дружба", "празднование", "радость"], meaning: "Дружба, радость общения" },
    { id: 39, name: "Четверка кубков", suit: "cups", arcana: "minor", keywords: ["апатия", "размышления", "неудовлетворенность"], meaning: "Эмоциональная пауза" },
    { id: 40, name: "Пятерка кубков", suit: "cups", arcana: "minor", keywords: ["потеря", "сожаление", "грусть"], meaning: "Потеря, сожаление" },
    { id: 41, name: "Шестерка кубков", suit: "cups", arcana: "minor", keywords: ["ностальгия", "детство", "прошлое"], meaning: "Ностальгия, воспоминания" },
    { id: 42, name: "Семерка кубков", suit: "cups", arcana: "minor", keywords: ["иллюзии", "выбор", "мечты"], meaning: "Много вариантов, иллюзии" },
    { id: 43, name: "Восьмерка кубков", suit: "cups", arcana: "minor", keywords: ["уход", "поиск", "разочарование"], meaning: "Поиск большего смысла" },
    { id: 44, name: "Девятка кубков", suit: "cups", arcana: "minor", keywords: ["удовлетворение", "счастье", "исполнение желаний"], meaning: "Эмоциональное удовлетворение" },
    { id: 45, name: "Десятка кубков", suit: "cups", arcana: "minor", keywords: ["семья", "гармония", "счастье"], meaning: "Семейное счастье" },
    { id: 46, name: "Паж кубков", suit: "cups", arcana: "minor", keywords: ["творчество", "романтика", "новые идеи"], meaning: "Творческое вдохновение" },
    { id: 47, name: "Рыцарь кубков", suit: "cups", arcana: "minor", keywords: ["романтика", "очарование", "предложение"], meaning: "Романтическое предложение" },
    { id: 48, name: "Королева кубков", suit: "cups", arcana: "minor", keywords: ["сострадание", "интуиция", "забота"], meaning: "Эмоциональная мудрость" },
    { id: 49, name: "Король кубков", suit: "cups", arcana: "minor", keywords: ["эмоциональный баланс", "мудрость", "контроль"], meaning: "Эмоциональный контроль" },
    { id: 50, name: "Туз мечей", suit: "swords", arcana: "minor", keywords: ["ясность", "новая идея", "прорыв"], meaning: "Ясность мышления, прорыв" },
    { id: 51, name: "Двойка мечей", suit: "swords", arcana: "minor", keywords: ["нерешительность", "тупик", "выбор"], meaning: "Трудный выбор" },
    { id: 52, name: "Тройка мечей", suit: "swords", arcana: "minor", keywords: ["боль", "разбитое сердце", "горе"], meaning: "Эмоциональная боль" },
    { id: 53, name: "Четверка мечей", suit: "swords", arcana: "minor", keywords: ["отдых", "восстановление", "пауза"], meaning: "Необходимость отдыха" },
    { id: 54, name: "Пятерка мечей", suit: "swords", arcana: "minor", keywords: ["конфликт", "поражение", "напряжение"], meaning: "Конфликт, напряжение" },
    { id: 55, name: "Шестерка мечей", suit: "swords", arcana: "minor", keywords: ["переход", "путешествие", "исцеление"], meaning: "Переход к лучшему" },
    { id: 56, name: "Семерка мечей", suit: "swords", arcana: "minor", keywords: ["хитрость", "стратегия", "обман"], meaning: "Стратегия, осторожность" },
    { id: 57, name: "Восьмерка мечей", suit: "swords", arcana: "minor", keywords: ["ограничения", "беспомощность", "ловушка"], meaning: "Ощущение ловушки" },
    { id: 58, name: "Девятка мечей", suit: "swords", arcana: "minor", keywords: ["тревога", "бессонница", "страх"], meaning: "Тревога, беспокойство" },
    { id: 59, name: "Десятка мечей", suit: "swords", arcana: "minor", keywords: ["конец", "предательство", "дно"], meaning: "Конец трудного периода" },
    { id: 60, name: "Паж мечей", suit: "swords", arcana: "minor", keywords: ["любознательность", "бдительность", "новые идеи"], meaning: "Любознательность, бдительность" },
    { id: 61, name: "Рыцарь мечей", suit: "swords", arcana: "minor", keywords: ["действие", "решительность", "амбиции"], meaning: "Решительное действие" },
    { id: 62, name: "Королева мечей", suit: "swords", arcana: "minor", keywords: ["независимость", "ясность", "проницательность"], meaning: "Ясность ума" },
    { id: 63, name: "Король мечей", suit: "swords", arcana: "minor", keywords: ["интеллект", "власть", "авторитет"], meaning: "Интеллектуальная власть" },
    { id: 64, name: "Туз пентаклей", suit: "pentacles", arcana: "minor", keywords: ["новые возможности", "процветание", "удача"], meaning: "Новые финансовые возможности" },
    { id: 65, name: "Двойка пентаклей", suit: "pentacles", arcana: "minor", keywords: ["баланс", "адаптация", "многозадачность"], meaning: "Баланс ресурсов" },
    { id: 66, name: "Тройка пентаклей", suit: "pentacles", arcana: "minor", keywords: ["командная работа", "мастерство", "обучение"], meaning: "Профессиональный рост" },
    { id: 67, name: "Четверка пентаклей", suit: "pentacles", arcana: "minor", keywords: ["контроль", "стабильность", "экономия"], meaning: "Финансовая стабильность" },
    { id: 68, name: "Пятерка пентаклей", suit: "pentacles", arcana: "minor", keywords: ["трудности", "потеря", "нужда"], meaning: "Финансовые трудности" },
    { id: 69, name: "Шестерка пентаклей", suit: "pentacles", arcana: "minor", keywords: ["щедрость", "благотворительность", "баланс"], meaning: "Давание и получение" },
    { id: 70, name: "Семерка пентаклей", suit: "pentacles", arcana: "minor", keywords: ["терпение", "ожидание", "оценка"], meaning: "Оценка прогресса" },
    { id: 71, name: "Восьмерка пентаклей", suit: "pentacles", arcana: "minor", keywords: ["мастерство", "труд", "детали"], meaning: "Усердная работа" },
    { id: 72, name: "Девятка пентаклей", suit: "pentacles", arcana: "minor", keywords: ["изобилие", "роскошь", "независимость"], meaning: "Материальное благополучие" },
    { id: 73, name: "Десятка пентаклей", suit: "pentacles", arcana: "minor", keywords: ["богатство", "наследство", "семья"], meaning: "Семейное богатство" },
    { id: 74, name: "Паж пентаклей", suit: "pentacles", arcana: "minor", keywords: ["обучение", "новые навыки", "возможности"], meaning: "Обучение новому" },
    { id: 75, name: "Рыцарь пентаклей", suit: "pentacles", arcana: "minor", keywords: ["надежность", "терпение", "практичность"], meaning: "Надежность, практичность" },
    { id: 76, name: "Королева пентаклей", suit: "pentacles", arcana: "minor", keywords: ["забота", "практичность", "процветание"], meaning: "Практическая мудрость" },
    { id: 77, name: "Король пентаклей", suit: "pentacles", arcana: "minor", keywords: ["успех", "бизнес", "богатство"], meaning: "Финансовый успех" }
];

const categoryTranslations = {
    career: "Карьера",
    love: "Отношения",
    money: "Финансы",
    general: "Общее"
};

function getRandomCards(count = 3) {
    const shuffled = [...tarotCards].sort(() => 0.5 - Math.random());
    return shuffled.slice(0, count);
}