const tarotCards = [
    { id: 0, name: "The Fool", nameEn: "The Fool", arcana: "major", keywords: ["new beginnings", "spontaneity", "freedom"], meaning: "New journey, innocence, spontaneity" },
    { id: 1, name: "The Magician", nameEn: "The Magician", arcana: "major", keywords: ["willpower", "skill", "concentration"], meaning: "Willpower, mastery, concentration" },
    { id: 2, name: "The High Priestess", nameEn: "The High Priestess", arcana: "major", keywords: ["intuition", "mystery", "subconscious"], meaning: "Intuition, subconscious, hidden knowledge" },
    { id: 3, name: "The Empress", nameEn: "The Empress", arcana: "major", keywords: ["fertility", "abundance", "nature"], meaning: "Abundance, fertility, harmony with nature" },
    { id: 4, name: "The Emperor", nameEn: "The Emperor", arcana: "major", keywords: ["authority", "structure", "control"], meaning: "Authority, structure, control" },
    { id: 5, name: "The Hierophant", nameEn: "The Hierophant", arcana: "major", keywords: ["tradition", "learning", "spirituality"], meaning: "Traditions, spiritual learning" },
    { id: 6, name: "The Lovers", nameEn: "The Lovers", arcana: "major", keywords: ["love", "harmony", "choice"], meaning: "Love, harmony, important choice" },
    { id: 7, name: "The Chariot", nameEn: "The Chariot", arcana: "major", keywords: ["victory", "control", "determination"], meaning: "Victory, determination, control" },
    { id: 8, name: "Strength", nameEn: "Strength", arcana: "major", keywords: ["courage", "compassion", "patience"], meaning: "Inner strength, patience" },
    { id: 9, name: "The Hermit", nameEn: "The Hermit", arcana: "major", keywords: ["introspection", "wisdom", "solitude"], meaning: "Self-reflection, seeking truth" },
    { id: 10, name: "Wheel of Fortune", nameEn: "Wheel of Fortune", arcana: "major", keywords: ["change", "destiny", "cycles"], meaning: "Change, turn of fate" },
    { id: 11, name: "Justice", nameEn: "Justice", arcana: "major", keywords: ["justice", "truth", "law"], meaning: "Justice, balance" },
    { id: 12, name: "The Hanged Man", nameEn: "The Hanged Man", arcana: "major", keywords: ["pause", "surrender", "new perspective"], meaning: "Pause, new perspective" },
    { id: 13, name: "Death", nameEn: "Death", arcana: "major", keywords: ["transformation", "ending", "rebirth"], meaning: "Transformation, end of cycle" },
    { id: 14, name: "Temperance", nameEn: "Temperance", arcana: "major", keywords: ["balance", "moderation", "harmony"], meaning: "Balance, moderation" },
    { id: 15, name: "The Devil", nameEn: "The Devil", arcana: "major", keywords: ["temptation", "addiction", "materialism"], meaning: "Temptation, material attachment" },
    { id: 16, name: "The Tower", nameEn: "The Tower", arcana: "major", keywords: ["destruction", "sudden change", "liberation"], meaning: "Sudden change, breaking illusions" },
    { id: 17, name: "The Star", nameEn: "The Star", arcana: "major", keywords: ["hope", "inspiration", "serenity"], meaning: "Hope, inspiration" },
    { id: 18, name: "The Moon", nameEn: "The Moon", arcana: "major", keywords: ["illusion", "intuition", "fear"], meaning: "Intuition, hidden fears" },
    { id: 19, name: "The Sun", nameEn: "The Sun", arcana: "major", keywords: ["joy", "success", "vitality"], meaning: "Joy, success, vitality" },
    { id: 20, name: "Judgement", nameEn: "Judgement", arcana: "major", keywords: ["rebirth", "calling", "forgiveness"], meaning: "Rebirth, inner calling" },
    { id: 21, name: "The World", nameEn: "The World", arcana: "major", keywords: ["completion", "wholeness", "achievement"], meaning: "Completion, achieving goals" },
    { id: 22, name: "Ace of Wands", suit: "wands", arcana: "minor", keywords: ["inspiration", "new idea", "energy"], meaning: "New inspiration, creative energy" },
    { id: 23, name: "Two of Wands", suit: "wands", arcana: "minor", keywords: ["planning", "decision", "future"], meaning: "Planning the future, choosing a path" },
    { id: 24, name: "Three of Wands", suit: "wands", arcana: "minor", keywords: ["expansion", "progress", "prospects"], meaning: "Progress, expanding horizons" },
    { id: 25, name: "Four of Wands", suit: "wands", arcana: "minor", keywords: ["celebration", "harmony", "home"], meaning: "Celebration, stability" },
    { id: 26, name: "Five of Wands", suit: "wands", arcana: "minor", keywords: ["conflict", "competition", "struggle"], meaning: "Conflict, competition" },
    { id: 27, name: "Six of Wands", suit: "wands", arcana: "minor", keywords: ["victory", "recognition", "success"], meaning: "Victory, recognition" },
    { id: 28, name: "Seven of Wands", suit: "wands", arcana: "minor", keywords: ["defense", "persistence", "challenge"], meaning: "Defending your position" },
    { id: 29, name: "Eight of Wands", suit: "wands", arcana: "minor", keywords: ["speed", "action", "movement"], meaning: "Fast forward movement" },
    { id: 30, name: "Nine of Wands", suit: "wands", arcana: "minor", keywords: ["resilience", "endurance", "boundaries"], meaning: "Persistence, protecting boundaries" },
    { id: 31, name: "Ten of Wands", suit: "wands", arcana: "minor", keywords: ["burden", "responsibility", "load"], meaning: "Heavy burden of responsibility" },
    { id: 32, name: "Page of Wands", suit: "wands", arcana: "minor", keywords: ["exploration", "enthusiasm", "news"], meaning: "New ideas, enthusiasm" },
    { id: 33, name: "Knight of Wands", suit: "wands", arcana: "minor", keywords: ["energy", "passion", "adventure"], meaning: "Energetic action" },
    { id: 34, name: "Queen of Wands", suit: "wands", arcana: "minor", keywords: ["confidence", "charisma", "independence"], meaning: "Confidence, charisma" },
    { id: 35, name: "King of Wands", suit: "wands", arcana: "minor", keywords: ["leadership", "vision", "entrepreneurship"], meaning: "Leadership, entrepreneurial spirit" },
    { id: 36, name: "Ace of Cups", suit: "cups", arcana: "minor", keywords: ["love", "emotions", "new feelings"], meaning: "New emotions, love" },
    { id: 37, name: "Two of Cups", suit: "cups", arcana: "minor", keywords: ["partnership", "connection", "harmony"], meaning: "Harmonious relationship" },
    { id: 38, name: "Three of Cups", suit: "cups", arcana: "minor", keywords: ["friendship", "celebration", "joy"], meaning: "Friendship, joyful connection" },
    { id: 39, name: "Four of Cups", suit: "cups", arcana: "minor", keywords: ["apathy", "contemplation", "dissatisfaction"], meaning: "Emotional pause" },
    { id: 40, name: "Five of Cups", suit: "cups", arcana: "minor", keywords: ["loss", "regret", "grief"], meaning: "Loss, regret" },
    { id: 41, name: "Six of Cups", suit: "cups", arcana: "minor", keywords: ["nostalgia", "childhood", "past"], meaning: "Nostalgia, memories" },
    { id: 42, name: "Seven of Cups", suit: "cups", arcana: "minor", keywords: ["illusion", "choice", "dreams"], meaning: "Many options, illusions" },
    { id: 43, name: "Eight of Cups", suit: "cups", arcana: "minor", keywords: ["departure", "search", "disappointment"], meaning: "Searching for deeper meaning" },
    { id: 44, name: "Nine of Cups", suit: "cups", arcana: "minor", keywords: ["satisfaction", "happiness", "wish fulfilled"], meaning: "Emotional satisfaction" },
    { id: 45, name: "Ten of Cups", suit: "cups", arcana: "minor", keywords: ["family", "harmony", "happiness"], meaning: "Family happiness" },
    { id: 46, name: "Page of Cups", suit: "cups", arcana: "minor", keywords: ["creativity", "romance", "new ideas"], meaning: "Creative inspiration" },
    { id: 47, name: "Knight of Cups", suit: "cups", arcana: "minor", keywords: ["romance", "charm", "proposal"], meaning: "Romantic proposal" },
    { id: 48, name: "Queen of Cups", suit: "cups", arcana: "minor", keywords: ["compassion", "intuition", "care"], meaning: "Emotional wisdom" },
    { id: 49, name: "King of Cups", suit: "cups", arcana: "minor", keywords: ["emotional balance", "wisdom", "control"], meaning: "Emotional control" },
    { id: 50, name: "Ace of Swords", suit: "swords", arcana: "minor", keywords: ["clarity", "new idea", "breakthrough"], meaning: "Clarity of thought, breakthrough" },
    { id: 51, name: "Two of Swords", suit: "swords", arcana: "minor", keywords: ["indecision", "stalemate", "choice"], meaning: "Difficult choice" },
    { id: 52, name: "Three of Swords", suit: "swords", arcana: "minor", keywords: ["pain", "heartbreak", "grief"], meaning: "Emotional pain" },
    { id: 53, name: "Four of Swords", suit: "swords", arcana: "minor", keywords: ["rest", "recovery", "pause"], meaning: "Need for rest" },
    { id: 54, name: "Five of Swords", suit: "swords", arcana: "minor", keywords: ["conflict", "defeat", "tension"], meaning: "Conflict, tension" },
    { id: 55, name: "Six of Swords", suit: "swords", arcana: "minor", keywords: ["transition", "journey", "healing"], meaning: "Transition to better" },
    { id: 56, name: "Seven of Swords", suit: "swords", arcana: "minor", keywords: ["cunning", "strategy", "deception"], meaning: "Strategy, caution" },
    { id: 57, name: "Eight of Swords", suit: "swords", arcana: "minor", keywords: ["restriction", "helplessness", "trap"], meaning: "Feeling trapped" },
    { id: 58, name: "Nine of Swords", suit: "swords", arcana: "minor", keywords: ["anxiety", "insomnia", "fear"], meaning: "Anxiety, worry" },
    { id: 59, name: "Ten of Swords", suit: "swords", arcana: "minor", keywords: ["ending", "betrayal", "rock bottom"], meaning: "End of difficult period" },
    { id: 60, name: "Page of Swords", suit: "swords", arcana: "minor", keywords: ["curiosity", "vigilance", "new ideas"], meaning: "Curiosity, vigilance" },
    { id: 61, name: "Knight of Swords", suit: "swords", arcana: "minor", keywords: ["action", "decisiveness", "ambition"], meaning: "Decisive action" },
    { id: 62, name: "Queen of Swords", suit: "swords", arcana: "minor", keywords: ["independence", "clarity", "perception"], meaning: "Clarity of mind" },
    { id: 63, name: "King of Swords", suit: "swords", arcana: "minor", keywords: ["intellect", "power", "authority"], meaning: "Intellectual authority" },
    { id: 64, name: "Ace of Pentacles", suit: "pentacles", arcana: "minor", keywords: ["new opportunity", "prosperity", "luck"], meaning: "New financial opportunity" },
    { id: 65, name: "Two of Pentacles", suit: "pentacles", arcana: "minor", keywords: ["balance", "adaptation", "multitasking"], meaning: "Balancing resources" },
    { id: 66, name: "Three of Pentacles", suit: "pentacles", arcana: "minor", keywords: ["teamwork", "skill", "learning"], meaning: "Professional growth" },
    { id: 67, name: "Four of Pentacles", suit: "pentacles", arcana: "minor", keywords: ["control", "stability", "saving"], meaning: "Financial stability" },
    { id: 68, name: "Five of Pentacles", suit: "pentacles", arcana: "minor", keywords: ["hardship", "loss", "need"], meaning: "Financial difficulties" },
    { id: 69, name: "Six of Pentacles", suit: "pentacles", arcana: "minor", keywords: ["generosity", "charity", "balance"], meaning: "Giving and receiving" },
    { id: 70, name: "Seven of Pentacles", suit: "pentacles", arcana: "minor", keywords: ["patience", "waiting", "assessment"], meaning: "Assessing progress" },
    { id: 71, name: "Eight of Pentacles", suit: "pentacles", arcana: "minor", keywords: ["mastery", "work", "details"], meaning: "Diligent work" },
    { id: 72, name: "Nine of Pentacles", suit: "pentacles", arcana: "minor", keywords: ["abundance", "luxury", "independence"], meaning: "Material well-being" },
    { id: 73, name: "Ten of Pentacles", suit: "pentacles", arcana: "minor", keywords: ["wealth", "inheritance", "family"], meaning: "Family wealth" },
    { id: 74, name: "Page of Pentacles", suit: "pentacles", arcana: "minor", keywords: ["learning", "new skills", "opportunity"], meaning: "Learning something new" },
    { id: 75, name: "Knight of Pentacles", suit: "pentacles", arcana: "minor", keywords: ["reliability", "patience", "practicality"], meaning: "Reliability, practicality" },
    { id: 76, name: "Queen of Pentacles", suit: "pentacles", arcana: "minor", keywords: ["care", "practicality", "prosperity"], meaning: "Practical wisdom" },
    { id: 77, name: "King of Pentacles", suit: "pentacles", arcana: "minor", keywords: ["success", "business", "wealth"], meaning: "Financial success" }
];

const categoryTranslations = {
    career: "Career",
    love: "Relationships",
    money: "Finances",
    general: "General"
};

function getRandomCards(count = 3) {
    const shuffled = [...tarotCards].sort(() => 0.5 - Math.random());
    return shuffled.slice(0, count);
}